gprep_site_settings.form:
  path: '/admin/config/system/gprep-site-settings'
  defaults:
    _form: '\Drupal\gprep_site_settings\Form\GprepSiteSettingsForm'
    _title: 'GPREP site settings'
  requirements:
    _permission: 'administer site configuration'

gprep_site_settings.emergency_toggle:
  path: '/admin/config/system/gprep-site-settings/emergency-toggle'
  defaults:
    _controller: '\Drupal\gprep_site_settings\Controller\EmergencyModeController::toggle'
  requirements:
    _permission: 'administer site configuration'
